CREATE TABLE GPS_DEVICE(
    GPS_DEVICE_ID VARCHAR(40) NOT NULL,
    GRS_DEVICE_NAME  VARCHAR(50),
    ACTIVATION_DATE DATE NOT NULL,
    EXPIRATION_DATE DATE,
    IS_ENABLED  CHAR(1) NOT NULL,
    PRIMARY KEY (GPS_DEVICE_ID)
);