CREATE TABLE ROLE(
	ROLE_ID INT NOT NULL AUTO_INCREMENT,
	ROLE_NAME VARCHAR(25) UNIQUE,
	ACCESS_LEVEL CHAR(1) NOT NULL,
	PRIMARY KEY(ROLE_ID)
);


CREATE TABLE USER_RIGHT(
	RIGHT_ID INT NOT NULL AUTO_INCREMENT,
	RIGHT_NAME VARCHAR(40) UNIQUE NOT NULL,
	PRIMARY KEY (RIGHT_ID)
);

CREATE TABLE ROLE_RIGHTS_XREF(
	ROLE_ID INT,
	RIGHT_ID INT,
	FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID),	
	FOREIGN KEY (RIGHT_ID) REFERENCES USER_RIGHT(RIGHT_ID)
);

CREATE TABLE GPS_DEVICE(
    GPS_DEVICE_ID VARCHAR(40) NOT NULL,
    GRS_DEVICE_NAME VARCHAR(50) ,
    ACTIVATION_DATE DATE NOT NULL,
    EXPIRATION_DATE DATE,
    IS_ENABLED  CHAR(1) NOT NULL,
    PRIMARY KEY (GPS_DEVICE_ID)
);

CREATE TABLE USERS (
	USER_ID INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(40) UNIQUE NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	IS_ENABLED CHAR(1) NOT NULL,
	CREATED_DATE DATE,
	CREATED_BY INT,
	LAST_MODIFIED_DATE DATE,
	MODIFIED_BY INT,
	INVALID_LOGIN_ATTEMPT INT NOT NULL,
	PRIMARY KEY(USER_ID)
);

CREATE TABLE USER_PROFILE(
	USER_PROFILE_ID INT NOT NULL AUTO_INCREMENT,
	USER_ID INT,
	FIRST_NAME VARCHAR(25) NOT NULL,
	MIDDLE_NAME VARCHAR(25),
	LAST_NAME VARCHAR(30) NOT NULL,
	ACCESS_LEVEL CHAR(1) NOT NULL,
	EMAIL_ID VARCHAR(50),
	MOBILE_NO INT,
	LANDLINE_NO INT,
	PRIMARY KEY(USER_PROFILE_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE ADDRESS(
	ADDRESS_ID INT NOT NULL AUTO_INCREMENT,
	USER_ID INT,
	ADDRESS1 VARCHAR(50) NOT NULL,
	ADDRESS2 VARCHAR(50) ,
	ADDRESS3 VARCHAR(50) NOT NULL,
	CITY VARCHAR(40) NOT NULL,
	STATE_CODE VARCHAR(5) NOT NULL,
	COUNTRY_CODE VARCHAR(5),
	PRIMARY KEY (ADDRESS_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)	
);

CREATE TABLE USERS_GPS_DEVICE_XREF(
	USER_ID INT,
	GPS_DEVICE_ID VARCHAR(40),
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),	
	FOREIGN KEY (GPS_DEVICE_ID) REFERENCES GPS_DEVICE(GPS_DEVICE_ID)	
);

CREATE TABLE GPS_DEVICE_LOCATION(
	GPS_DEVICE_ID VARCHAR(40) NOT NULL,
	LONGITUDE DOUBLE(16,4),
	LATITUDE DOUBLE(16,4),
	POSITION_TIME DATETIME,
	FOREIGN KEY (GPS_DEVICE_ID) REFERENCES GPS_DEVICE(GPS_DEVICE_ID)		
);

